# Generated by Django 5.2 on 2025-04-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='唯一标识符')),
                ('big_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='大类型')),
                ('type', models.CharField(blank=True, max_length=32, null=True, verbose_name='类型')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='名称')),
                ('img', models.CharField(blank=True, max_length=255, null=True, verbose_name='图片链接')),
                ('peiliao', models.CharField(blank=True, max_length=255, null=True, verbose_name='配料')),
                ('zz', models.CharField(blank=True, max_length=25, null=True, verbose_name='制作步骤')),
                ('imgze', models.CharField(blank=True, max_length=255, null=True, verbose_name='制作步骤图片链接')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='链接')),
                ('sc', models.CharField(blank=True, max_length=36, null=True, verbose_name='食材')),
                ('cat', models.CharField(blank=True, max_length=32, null=True, verbose_name='分类')),
                ('num', models.CharField(blank=True, max_length=3, null=True, verbose_name='数量')),
            ],
            options={
                'verbose_name': '美食管理',
                'verbose_name_plural': '美食管理',
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=31, primary_key=True, serialize=False, verbose_name='用户ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=32, null=True, verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
    ]
